# Generated by Django 5.2 on 2025-04-29 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='place')),
                ('time', models.TimeField(verbose_name='time')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='reward')),
                ('lead_time', models.DurationField(verbose_name='lead time')),
                ('is_public', models.BooleanField(default=False, verbose_name='public')),
                ('action', models.CharField(max_length=255, verbose_name='action')),
                ('pleasant', models.BooleanField(verbose_name='pleasant')),
                ('periodicity', models.CharField(choices=[('week', 'Every week'), ('3 days', 'Every 3 days'), ('day', 'Every day')], default='day', max_length=30, verbose_name='periodicity')),
                ('related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_habit', to='habit.habit', verbose_name='related')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habit', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
